'''
Compare the result of dark noise and laser
'''
import pandas as pd, numpy as np
import h5py
import matplotlib.pyplot as plt
plt.style.use('./journal.mplstyle')
from matplotlib.ticker import MultipleLocator
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib import cm
import argparse
import config
import os
ADC2mV = config.ADC2mV
psr = argparse.ArgumentParser()
psr.add_argument('-i', dest='ipt', default='ExPMT/PMTSummary.csv', help='input csv')
psr.add_argument('-o', dest='opt', default='ExPMT/PMTSummary.pdf', help='output csv')
psr.add_argument('--run', type=int, default=-1, help='run number; default using merge result')
psr.add_argument('--dir', default='ExPMT', help='directory of PMT results')
args = psr.parse_args()
excludedPMT = np.loadtxt('ExPMT/ExcludePMT.csv', dtype=str)
if args.run == -1:
    # all pmt
    pmtcsv = pd.read_csv(args.ipt)
    isexclude = np.array([(pmt not in excludedPMT) for pmt in pmtcsv['PMT'].values])
    ismcp = np.array([pmt.startswith('PM') for pmt in pmtcsv['PMT'].values])
    selectHama = (~ismcp) & isexclude
    selectMCP = ismcp & isexclude
    with PdfPages(args.opt) as pdf:
        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['Gain_DR'], pmtcsv[selectHama]['Gain'], xerr=np.sqrt(pmtcsv[selectHama]['Gain_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['GainVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['Gain_DR'], pmtcsv[selectMCP]['Gain'], xerr=np.sqrt(pmtcsv[selectMCP]['Gain_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['GainVar']), fmt='o', color='r', label='MCP PMT')
        ax.axline((np.mean(pmtcsv[selectMCP]['Gain']), np.mean(pmtcsv[selectMCP]['Gain'])), linestyle='--', slope=1)
        ax.set_xlabel('$G_1$ of dark noise stage')
        ax.set_ylabel('$G_1$ of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        # fig, ax = plt.subplots()
        # ax.scatter(pmtcsv[selectHama]['GainSigma_DR'], pmtcsv[selectHama]['GainSigma'], color='g', label='Reference PMT')
        # ax.scatter(pmtcsv[selectMCP]['GainSigma_DR'], pmtcsv[selectMCP]['GainSigma'], color='r', label='MCP PMT')
        # ax.axline((0.3, 0.3), slope=1)
        # ax.set_xlabel('Gain Sigma of dark noise stage')
        # ax.set_ylabel('Gain Sigma of trigger stage')
        # ax.legend()
        # pdf.savefig(fig)
        # plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['Res_DR'], pmtcsv[selectHama]['Res'], xerr=np.sqrt(pmtcsv[selectHama]['Res_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['ResVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['Res_DR'], pmtcsv[selectMCP]['Res'], xerr=np.sqrt(pmtcsv[selectMCP]['Res_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['ResVar']), fmt='o', color='r', label='MCP PMT')
        ax.axline((0.27, 0.27), linestyle='--', slope=1)
        ax.set_xlabel('$\mathrm{Res}_1$ of dark noise stage')
        ax.set_ylabel('$\mathrm{Res}_1$ of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['chargeMu_DR']/50/1.6*ADC2mV, pmtcsv[selectHama]['chargeMu']/50/1.6*ADC2mV, xerr=np.sqrt(pmtcsv[selectHama]['chargeMu_DRVar'])/50/1.6*ADC2mV, yerr=np.sqrt(pmtcsv[selectHama]['chargeMuVar'])/50/1.6*ADC2mV, fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['chargeMu_DR']/50/1.6*ADC2mV, pmtcsv[selectMCP]['chargeMu']/50/1.6*ADC2mV, xerr=np.sqrt(pmtcsv[selectMCP]['chargeMu_DRVar'])/50/1.6*ADC2mV, yerr=np.sqrt(pmtcsv[selectMCP]['chargeMuVar'])/50/1.6*ADC2mV, fmt='o', color='r', label='MCP PMT')
        ax.axline((np.mean(pmtcsv[selectMCP]['chargeMu']/50/1.6*ADC2mV), np.mean(pmtcsv[selectMCP]['chargeMu']/50/1.6*ADC2mV)), linestyle='--', slope=1)
        ax.set_xlabel('$G$ of dark noise stage')
        ax.set_ylabel('$G$ of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['chargeMu']/50/1.6*ADC2mV, pmtcsv[selectHama]['chargeRes'], xerr=np.sqrt(pmtcsv[selectHama]['chargeMuVar'])/50/1.6*ADC2mV, yerr=np.sqrt(pmtcsv[selectHama]['chargeResVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['chargeMu']/50/1.6*ADC2mV, pmtcsv[selectMCP]['chargeRes'], xerr=np.sqrt(pmtcsv[selectMCP]['chargeMuVar'])/50/1.6*ADC2mV, yerr=np.sqrt(pmtcsv[selectMCP]['chargeResVar']), fmt='o', color='r', label='MCP PMT')
        ax.set_xlabel('$G$ of trigger stage')
        ax.set_ylabel('$\mathrm{Res}$ of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['chargeRes_DR'], pmtcsv[selectHama]['chargeRes'], xerr=np.sqrt(pmtcsv[selectHama]['chargeRes_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['chargeResVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['chargeRes_DR'], pmtcsv[selectMCP]['chargeRes'], xerr=np.sqrt(pmtcsv[selectMCP]['chargeRes_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['chargeResVar']), fmt='o', color='r', label='MCP PMT')
        ax.axline((0.7, 0.7), linestyle='--', slope=1)
        ax.set_xlabel('$\mathrm{Res}$ of dark noise stage')
        ax.set_ylabel('$\mathrm{Res}$ of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['PV_DR'], pmtcsv[selectHama]['PV'], xerr=np.sqrt(pmtcsv[selectHama]['PV_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['PVVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['PV_DR'], pmtcsv[selectMCP]['PV'], xerr=np.sqrt(pmtcsv[selectMCP]['PV_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['PVVar']), fmt='o', color='r', label='MCP PMT')
        ax.axline((np.mean(pmtcsv[selectMCP]['PV']), np.mean(pmtcsv[selectMCP]['PV'])), linestyle='--', slope=1)
        ax.set_xlabel('P/V of dark noise stage')
        ax.set_ylabel('P/V of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['Rise_DR'], pmtcsv[selectHama]['Rise'], xerr=np.sqrt(pmtcsv[selectHama]['Rise_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['RiseVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['Rise_DR'], pmtcsv[selectMCP]['Rise'], xerr=np.sqrt(pmtcsv[selectMCP]['Rise_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['RiseVar']), fmt='o', color='r', label='MCP PMT')
        ax.axline((np.mean(pmtcsv[selectMCP]['Rise']), np.mean(pmtcsv[selectMCP]['Rise'])), linestyle='--', slope=1)
        ax.set_xlabel('$t_r$/ns of dark noise stage')
        ax.set_ylabel('$t_r$/ns of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['Fall_DR'], pmtcsv[selectHama]['Fall'], xerr=np.sqrt(pmtcsv[selectHama]['Fall_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['FallVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['Fall_DR'], pmtcsv[selectMCP]['Fall'], xerr=np.sqrt(pmtcsv[selectMCP]['Fall_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['FallVar']), fmt='o', color='r', label='MCP PMT')
        ax.axline((np.mean(pmtcsv[selectMCP]['Fall']), np.mean(pmtcsv[selectMCP]['Fall'])), linestyle='--', slope=1)
        ax.set_xlabel('$t_f$/ns of dark noise stage')
        ax.set_ylabel('$t_f$/ns of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['FWHM_DR'], pmtcsv[selectHama]['FWHM'], xerr=np.sqrt(pmtcsv[selectHama]['FWHM_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['FWHMVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['FWHM_DR'], pmtcsv[selectMCP]['FWHM'], xerr=np.sqrt(pmtcsv[selectMCP]['FWHM_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['FWHMVar']), fmt='o', color='r', label='MCP PMT')
        ax.axline((np.mean(pmtcsv[selectMCP]['FWHM']), np.mean(pmtcsv[selectMCP]['FWHM'])), linestyle='--', slope=1)
        ax.set_xlabel('FWHM/ns of dark noise stage')
        ax.set_ylabel('FWHM/ns of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectMCP]['PDE'], pmtcsv[selectMCP]['DCR'], xerr=np.sqrt(pmtcsv[selectMCP]['PDEVar']), yerr=np.sqrt(pmtcsv[selectMCP]['DCRVar']), fmt='o', color='r', label='MCP PMT')
        ax.axhline(np.average(pmtcsv[selectMCP]['DCR']), linestyle='--', label='Average DCR of MCP PMT')
        ax.set_xlabel('relative PDE')
        ax.set_ylabel('DCR/kHz')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectHama]['chargeRes'], pmtcsv[selectHama]['TTS_bin'], xerr=np.sqrt(pmtcsv[selectHama]['Res_DRVar']), yerr=np.sqrt(pmtcsv[selectHama]['ResVar']), fmt='o', color='g', label='Reference PMT')
        ax.errorbar(pmtcsv[selectMCP]['chargeRes'], pmtcsv[selectMCP]['TTS_bin'], xerr=np.sqrt(pmtcsv[selectMCP]['Res_DRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['ResVar']), fmt='o', color='r', label='MCP PMT')
        ax.axhline(np.average(pmtcsv[selectMCP]['TTS_bin']), linestyle='--', label='Average TTS of MCP PMT')
        ax.set_xlabel('Single PE resolution of trigger stage')
        ax.set_ylabel('TTS/ns')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        # ax.errorbar(pmtcsv[selectHama]['DCR'], pmtcsv[selectHama]['Pre'], xerr=np.sqrt(pmtcsv[selectHama]['DCRVar']), yerr=np.sqrt(pmtcsv[selectHama]['PreVar']), fmt='o', color='g', label='After pulse 300-1000ns')
        ax.errorbar(pmtcsv[selectMCP]['DCR'], pmtcsv[selectMCP]['Pre'], xerr=np.sqrt(pmtcsv[selectMCP]['DCRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['PreVar']), fmt='o', color='r')
        ax.axhline(np.average(pmtcsv[selectMCP]['Pre']), linestyle='--', label='Average pre-pulse ratio')
        ax.set_xlabel('DCR/kHz in dark noise stage')
        ax.set_ylabel('Pre pulse ratio in [-250,-50] ns')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        # ax.errorbar(pmtcsv[selectHama]['DCR'], pmtcsv[selectHama]['After1'] + pmtcsv[selectHama]['After2'], xerr=np.sqrt(pmtcsv[selectHama]['DCRVar']), yerr=np.sqrt(pmtcsv[selectHama]['After1Var']+pmtcsv[selectHama]['After2Var']), fmt='o', color='g', label='After pulse 300-1000ns')
        ax.errorbar(pmtcsv[selectMCP]['DCR'], pmtcsv[selectMCP]['After1'] + pmtcsv[selectMCP]['After2'], xerr=np.sqrt(pmtcsv[selectMCP]['DCRVar']), yerr=np.sqrt(pmtcsv[selectMCP]['After1Var']+pmtcsv[selectMCP]['After2Var']), fmt='o', color='r')
        ax.axhline(np.average(pmtcsv[selectMCP]['After1'] + pmtcsv[selectMCP]['After2']), linestyle='--', label='Average After pulse ratio')
        ax.set_xlabel('DCR/kHz in dark noise stage')
        ax.set_ylabel('After pulse ratio in [300,10000] ns')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        ax.errorbar(pmtcsv[selectMCP]['ser_tau'], pmtcsv[selectMCP]['ser_sigma'], xerr=np.sqrt(pmtcsv[selectMCP]['ser_tauVar']), yerr=np.sqrt(pmtcsv[selectMCP]['ser_sigmaVar']), fmt='o', color='r')
        ax.set_xlabel('$\sigma_{\mathrm{ser}}$ of trigger stage')
        ax.set_ylabel(r'$\tau_{\mathrm{ser}}$ of trigger stage')
        ax.legend()
        pdf.savefig(fig)
        plt.close()

        # 绘制后脉冲峰比例
        fig, ax = plt.subplots()
        for pmt in pmtcsv['PMT'].values:
            if pmt.startswith('PM'):
                with h5py.File(args.dir+'/'+pmt+'/laser.h5', 'r') as ipt:
                    afterpulse = ipt['AfterPulse'][:]
                ax.plot(afterpulse['t'], afterpulse['pv']/afterpulse['pv'][0], marker='o')
                print(pmt, afterpulse['t'], afterpulse['pv']/afterpulse['pv'][0])
        ax.set_xlabel('time of peaks of after pulse')
        ax.set_ylabel(r'$\frac{A_i}{A_1}$')
        ax.xaxis.set_minor_locator(MultipleLocator(100))
        pdf.savefig(fig)
        plt.close()

        fig, ax = plt.subplots()
        pdegrid = np.arange(0.9, 2, 0.01)
        resgrid = np.arange(0.2, 1, 0.01)
        X, Y = np.meshgrid(pdegrid, resgrid)
        resolutions = np.sqrt((1+Y**2)/X)
        im = ax.pcolormesh(X, Y, resolutions)
        CS = ax.contour(X,Y, resolutions, origin='lower', cmap='flag')
        ax.scatter(pmtcsv[selectMCP]['PDE'], pmtcsv[selectMCP]['chargeRes'], color='g', label='MCP')
        ax.scatter([1], [pmtcsv.set_index('PMT').loc['CR365']['chargeRes']], color='r', label='Reference PMT')
        print(pmtcsv[selectHama]['PDE'],  pmtcsv[selectHama]['chargeRes'])
        ax.clabel(CS, CS.levels,  # label every second level
              inline=True, fmt='%.1f', fontsize=14)
        ax.set_xlabel('relative PDE')
        ax.set_ylabel('single PE resolution')
        ax.legend()
        pdf.savefig(fig)
        plt.close()
        print('DCR {:.2f}'.format(np.mean(pmtcsv[selectMCP]['DCR'])))
        print('TTS {:.2f}'.format(np.mean(pmtcsv[selectMCP]['TTS'])))
        print('PDE {:.2f}'.format(np.mean(pmtcsv[selectMCP]['PDE'])))
        print('Res1 {:.2f}'.format(np.mean(pmtcsv[selectMCP]['Res'])))
        print('Res {:.2f}'.format(np.mean(pmtcsv[selectMCP]['chargeRes'])))
        print('Gain {:.2f}'.format(np.mean(pmtcsv[selectMCP]['chargeMu']/50/1.6*ADC2mV)))
        print('tau {:.2f}'.format(np.mean(pmtcsv[selectMCP]['ser_tau'])))
        print('sigma {:.2f}'.format(np.mean(pmtcsv[selectMCP]['ser_sigma'])))
