#!/bin/bash
# 执行 SK 官方环境的代码

case $(hostname) in
    bat)
        A8="bwrap --ro-bind /var/lib/lxc/a8/rootfs/ / --dev /dev --tmpfs /tmp --bind /mnt/stage /mnt/stage --bind /home /home --bind /usr/local /usr/local --bind /ackermann/SK/disk01 /disk01"
        ;;
    sukap*)
	A8="env -i"
        ;;
esac

# printf 的用法参考自 https://stackoverflow.com/a/50367671/391057
# %q Causes printf to output the corresponding argument in a format that can be reused as shell input.
${A8} bash --noprofile --norc <<EOF
source /usr/local/sklib_gcc8/bashenv_gcc8_skofl_23b+atmpd_23b
source /usr/local/sklib_gcc8/skofl_23b/env.sh
exec $(printf ' %q' "$@")
EOF
