import matplotlib.pyplot as plt
import h5py, argparse
import numpy as np
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import matplotlib.colors as colors
from matplotlib.backends.backend_pdf import PdfPages
psr = argparse.ArgumentParser()
psr.add_argument('-i', dest='ipt', help='input h5 file')
psr.add_argument('-o', dest='opt', help='output png file')
psr.add_argument('-c', dest='channel', nargs='+', default=[0,1],help='channel used in DAQ')
args = psr.parse_args()
#plt.style.use('fivethirtyeight')
info = []
with h5py.File(args.ipt, 'r') as ipt:
    waveformLength = ipt.attrs['waveformLength']
    #waveformLength = 1500
    for j in range(len(args.channel)):
        print(j)
        info.append(ipt['ch{}'.format(args.channel[j])][:])
rangemin =-100
rangemax = 500
bins = rangemax-rangemin

# set the figure appearance
props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
jet = plt.cm.jet
newcolors = jet(np.linspace(0, 1, 32768))
white = np.array([1, 1, 1, 0.5])
newcolors[0, :] = white
cmap = ListedColormap(newcolors)
print('begin plot')
pdf = PdfPages(args.opt)
for j in range(len(args.channel)):
    '''
    fig, ax = plt.subplots()
    ax.set_title('charge distribution')
    rangemin = int(np.min(info[j]['allCharge'])-1)
    rangemax = int(np.max(info[j]['allCharge'])+1)
    bins = rangemax-rangemin
    ax.hist(info[j]['allCharge'],histtype='step', bins=bins, range=[rangemin, rangemax], label='all charge integrate')
    ax.hist(info[j]['minPeakCharge'],histtype='step', bins=bins, range=[rangemin, rangemax], label='[peak-50, peak+50] charge integrate')
    ax.set_xlabel('charge/mVns')
    ax.set_ylabel('entries')
    ax.legend()
    ax.set_yscale('log')
    plt.savefig('{}/{}charge.png'.format(args.opt,args.channel[j]))
    ax.set_ylim([0,4000])
    ax.set_xlim([10, 400])
    ax.set_yscale('linear')
    plt.savefig('{}/{}chargeLinear.png'.format(args.opt,args.channel[j]))
    plt.close()
    '''
    fig, ax = plt.subplots()
    ax.set_title('peak height distribution')
    h = ax.hist(info[j]['minPeak'],histtype='step', bins=1000, label='baseline - peak')
    print('peak height max:{};max index {}; part of peak {}'.format(np.max(h[0]), np.argmax(h[0]), h[0][:(np.argmax(h[0])+5)]))
    ax.set_xlabel('peak height/mV')
    ax.set_ylabel('entries')
    ax.legend()
    # plt.savefig('{}/{}minpeakLinear.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}minpeak.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    # min peak position
    fig, ax = plt.subplots()
    ax.set_title('peak position distribution')
    h = ax.hist(info[j]['minPeakPos'],histtype='step', bins=waveformLength, range=[0,waveformLength], label='the largest peak pos')
    print('h shape:{};max index {}'.format(h[0].shape,np.argmax(h[0])))
    ax.set_xlabel('peak position/ns')
    ax.set_ylabel('entries')
    ax.legend()
    # plt.savefig('{}/{}minpeakposLinear.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}minpeakpos.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    
    fig, ax = plt.subplots()
    ax.set_title('peak position distribution')
    h = ax.hist(info[j]['minPeakPos'][(info[j]['minPeak']>5)],histtype='step', bins=waveformLength, range=[0,waveformLength], label='the largest peak pos')
    print('h shape:{};max index {}'.format(h[0].shape,np.argmax(h[0])))
    ax.set_xlabel('peak position/ns')
    ax.set_ylabel('entries')
    ax.legend()
    # plt.savefig('{}/{}minpeakposCutLinear.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}minpeakposCut.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    # min peak position and peak height distribution
    fig, ax = plt.subplots()
    ax.set_title('peakPos-peakHeight')
    h = ax.hist2d(info[j]['minPeakPos'],info[j]['minPeak'],range=[[0,waveformLength],[0,50]], bins=[int(waveformLength/100), 100], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('peakPos/ns')
    ax.set_ylabel('peakHeight/mV')
    # plt.savefig('{}/{}peakPos-peakHeight.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    # min peak charge and peak height distribution
    fig, ax = plt.subplots()
    ax.set_title('peakCharge-peakHeight')
    h = ax.hist2d(info[j]['minPeakCharge'],info[j]['minPeak'],range=[[0,400],[0,50]], bins=[400, 50], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('peakCharge/nsmV')
    ax.set_ylabel('peakHeight/mV')
    # plt.savefig('{}/{}peakCharge-peakHeight.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    fig, ax = plt.subplots()
    ax.set_title('peakCharge-peakHeight')
    h = ax.hist2d(info[j]['minPeakCharge'],info[j]['minPeak'],range=[[0,4500],[0,1000]], bins=[450, 100],norm=colors.LogNorm(), cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('peakCharge/nsmV')
    ax.set_ylabel('peakHeight/mV')
    # plt.savefig('{}/{}peakCharge-peakHeightLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    
    fig, ax = plt.subplots()
    ax.set_title('peakCharge-peakHeight')
    h = ax.hist2d(info[j]['minPeakCharge'],info[j]['minPeak'],range=[[35,4000],[3,998]], bins=[793, 199], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('peakCharge/nsmV')
    ax.set_ylabel('peakHeight/mV')
    # plt.savefig('{}/{}peakCharge-peakHeightCut1.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    fig, ax = plt.subplots()
    ax.set_title('peakCharge-peakHeight')
    h = ax.hist2d(info[j]['minPeakCharge'],info[j]['minPeak'],range=[[35,1000],[3,75]], bins=[965, 72], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('peakCharge/nsmV')
    ax.set_ylabel('peakHeight/mV')
    # plt.savefig('{}/{}peakCharge-peakHeightCut.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    # baseline and std distribution
    fig, ax = plt.subplots()
    ax.set_title('baseline-std')
    h = ax.hist2d(info[j]['baseline'],info[j]['std'], bins=[100,100], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('baseline/mV')
    ax.set_ylabel('std/mV')
    # plt.savefig('{}/{}base-std.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    # baseline
    fig, ax = plt.subplots()
    ax.set_title('baseline')
    ax.hist(info[j]['baseline'],histtype='step',bins=100, label='baseline')
    ax.set_xlabel('baseline/mV')
    ax.set_ylabel('entries')
    ax.set_yscale('log')
    ax.legend()
    # plt.savefig('{}/{}baselineLinear.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    # std
    fig, ax = plt.subplots()
    ax.set_title('std distribution')
    ax.hist(info[j]['std'],histtype='step', bins=100, label='std')
    ax.set_xlabel('std/mV')
    ax.set_ylabel('entries')
    ax.legend()
    ax.set_yscale('log')
    # plt.savefig('{}/{}stdLinear.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    plt.close()
    
    # risetime and downtime
    fig, ax = plt.subplots()
    ax.set_title('rise time distribution')
    ax.hist(info[j]['riseTime'][info[j]['minPeak']>5],histtype='step',bins=40, range=[0,40], label='risingtime')
    ax.set_xlabel('riseTime/ns')
    ax.set_ylabel('entries')
    ax.legend()
    #ax.set_xlim([1,40])
    # plt.savefig('{}/{}risetime.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}risetimeLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    plt.close()

    fig, ax = plt.subplots()
    ax.set_title('rise time distribution')
    ax.hist(info[j]['riseTime'][(info[j]['minPeak']>5)&(info[j]['minPeak']<40)],histtype='step',bins=40, range=[0,40], label='risingtime')
    ax.set_xlabel('riseTime/ns')
    ax.set_ylabel('entries')
    ax.legend()
    #ax.set_xlim([1,40])
    # plt.savefig('{}/{}risetimeUlimit.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}risetimeUlimitLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    plt.close()

    fig, ax = plt.subplots()
    ax.set_title('down time distribution')
    ax.hist(info[j]['downTime'][info[j]['minPeak']>5],histtype='step',bins=40, range=[0,40], label='downtime')
    ax.set_xlabel('downTime/ns')
    ax.set_ylabel('entries')
    ax.legend()
    #ax.set_xlim([1,40])
    # plt.savefig('{}/{}downTime.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}downtimeLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    fig, ax = plt.subplots()
    ax.set_title('down time distribution')
    ax.hist(info[j]['downTime'][(info[j]['minPeak']>5)&(info[j]['minPeak']<40)],histtype='step',bins=40, range=[0,40], label='downtime')
    ax.set_xlabel('downTime/ns')
    ax.set_ylabel('entries')
    ax.legend()
    #ax.set_xlim([1,40])
    # plt.savefig('{}/{}downTimeUlimit.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}downtimeUlimitLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)

    fig, ax = plt.subplots()
    ax.set_title('FWHM distribution')
    ax.hist(info[j]['FWHM'][info[j]['minPeak']>5],histtype='step',bins=40, range=[0,40], label='FWHM')
    ax.set_xlabel('FWHM/ns')
    ax.set_ylabel('entries')
    ax.legend()
    #ax.set_xlim([1,40])
    # plt.savefig('{}/{}FWHM.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}FWHMLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    fig, ax = plt.subplots()
    ax.set_title('FWHM distribution')
    ax.hist(info[j]['FWHM'][(info[j]['minPeak']>5)&(info[j]['minPeak']<40)],histtype='step',bins=40, range=[0,40], label='FWHM')
    ax.set_xlabel('FWHM/ns')
    ax.set_ylabel('entries')
    ax.legend()
    #ax.set_xlim([1,40])
    # plt.savefig('{}/{}FWHMUlimit.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}FWHMUlimitLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    
    fig, ax = plt.subplots()
    ax.set_title('FWHM-charge')
    h = ax.hist2d(info[j]['minPeakCharge'][(info[j]['minPeak']>5)],info[j]['FWHM'][(info[j]['minPeak']>5)], bins=[1000,20], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('charge/mVns')
    ax.set_ylabel('FWHM/ns')
    # plt.savefig('{}/{}FWHM-charge.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    
    fig, ax = plt.subplots()
    ax.set_title('FWHM-charge')
    h = ax.hist2d(info[j]['minPeakCharge'][(info[j]['minPeak']>5)&(info[j]['minPeakCharge']<8000)],info[j]['FWHM'][(info[j]['minPeak']>5)&(info[j]['minPeakCharge']<8000)], bins=[1000,20], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('charge/mVns')
    ax.set_ylabel('FWHM/ns')
    # plt.savefig('{}/{}FWHM-chargeCut.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    
    fig, ax = plt.subplots()
    ax.set_title('tot distribution')
    ax.hist(info[j][info[j]['minPeak']>5]['end5mV']-info[j][info[j]['minPeak']>5]['begin5mV'],histtype='step',bins=40, range=[0,40], label='tot')
    ax.set_xlabel('tot/ns')
    ax.set_ylabel('entries')
    ax.legend()
    #ax.set_xlim([1,40])
    # plt.savefig('{}/{}tot.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    ax.set_yscale('log')
    # plt.savefig('{}/{}totLog.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    
    fig, ax = plt.subplots()
    ax.set_title('charge-tot')
    h = ax.hist2d(info[j]['minPeakCharge'][(info[j]['minPeak']>5)],info[j][(info[j]['minPeak']>5)]['end5mV']-info[j][info[j]['minPeak']>5]['begin5mV'], bins=[1000,30], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('charge/mVns')
    ax.set_ylabel('tot/ns')
    # plt.savefig('{}/{}tot-charge.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
    
    fig, ax = plt.subplots()
    ax.set_title('charge-tot charge<{}'.format(1000))
    h = ax.hist2d(info[j]['minPeakCharge'][(info[j]['minPeak']>5)&(info[j]['minPeakCharge']<1000)],info[j][(info[j]['minPeak']>5)&(info[j]['minPeakCharge']<1000)]['end5mV']-info[j][(info[j]['minPeak']>5)&(info[j]['minPeakCharge']<1000)]['begin5mV'], bins=[200,30], cmap=cmap)
    fig.colorbar(h[3], ax=ax)
    ax.set_xlabel('charge/mVns')
    ax.set_ylabel('tot/ns')
    # plt.savefig('{}/{}tot-chargeCut.png'.format(args.opt,args.channel[j]))
    pdf.savefig(fig)
pdf.close()